name: Generate GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}]  # every day at midnight UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          config_timezone: Asia/Kolkata
